# Extra env variables
# env = MY_GLOBAL_ENV,setting
env = OMARCHY_SCREENSHOT_DIR,$HOME/Nextcloud/Pictures/Screenshots
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
